import { isValidElement } from "react";
import { describe, expect, it, vi } from "vitest";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "geist-sans" }),
  Geist_Mono: () => ({ variable: "geist-mono" }),
}));

import RootLayout, { metadata } from "./layout";

describe("RootLayout", () => {
  it("exports default metadata", () => {
    expect(metadata).toMatchObject({
      title: "Create Next App",
      description: "Generated by create next app",
    });
  });

  it("renders html and body wrappers around children", () => {
    const element = RootLayout({ children: "content" });

    expect(isValidElement(element)).toBe(true);
    expect(element.type).toBe("html");
    expect(element.props).toMatchObject({
      lang: "en",
      className: "geist-sans geist-mono h-full antialiased",
    });
  });
});
